// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngwshzmqoixsocrbulin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nd3Noem1xb2l4c29jcmJ1bGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDQ4ODQsImV4cCI6MjA2MjEyMDg4NH0.MJTGPFJ0z-6v9wobnQUIToewtDIbFKUO_qSvgp7AvFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);